-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.cliente
(
    id_cliente integer NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default",
    direccion character varying(255) COLLATE pg_catalog."default",
    telefono character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT cliente_pkey PRIMARY KEY (id_cliente)
);

CREATE TABLE IF NOT EXISTS public.detallefactura
(
    id_detalle integer NOT NULL,
    id_factura integer,
    id_producto integer,
    cantidad integer,
    "precio " integer,
    iva numeric(5, 0),
    sub_total numeric,
    CONSTRAINT detallefactura_pkey PRIMARY KEY (id_detalle)
);

CREATE TABLE IF NOT EXISTS public.factura
(
    id_factura integer NOT NULL,
    id_cliente integer,
    fecha date,
    total numeric(10, 2),
    num_factura integer NOT NULL DEFAULT nextval('factura_num_factura_seq'::regclass),
    sub_total numeric,
    CONSTRAINT factura_pkey PRIMARY KEY (id_factura)
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id_producto integer NOT NULL,
    nombre character varying(255) COLLATE pg_catalog."default",
    precio numeric(10, 2),
    CONSTRAINT producto_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.usuario
(
    id_usuario integer NOT NULL,
    correo_usuario character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

ALTER TABLE IF EXISTS public.detallefactura
    ADD CONSTRAINT detallefactura_id_factura_fkey FOREIGN KEY (id_factura)
    REFERENCES public.factura (id_factura) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.detallefactura
    ADD CONSTRAINT detallefactura_id_producto_fkey FOREIGN KEY (id_producto)
    REFERENCES public.producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.factura
    ADD CONSTRAINT factura_id_cliente_fkey FOREIGN KEY (id_cliente)
    REFERENCES public.cliente (id_cliente) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;